apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-system
  namespace: default
spec:
  selector:
    matchLabels:
      app: healthcare-system
  replicas: 1
  template:
    metadata:
      name: healthcare-system
      labels:
        app: healthcare-system
    spec:
      containers:
      - name: healthcare-system
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: postgres-secrets
                 key: password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: eate2020/healthcare-system:0.0.1